apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: gomall-cart:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8883
          env:
            - name: GO_ENV
              value: k8s
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: root
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: http://jaeger:4317
---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    app: cart
  ports:
    - name: rpc
      port: 8883
      targetPort: 8883
