apiVersion: v1
kind: Service
metadata:
  name: etcd-headless
spec:
  clusterIP: None
  selector:
    app: etcd
  ports:
  - name: client
    port: 2379
    targetPort: client
    protocol: TCP
  - name: peer
    port: 2380
    targetPort: peer
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
spec:
  selector:
    app: etcd
  ports:
  - name: client
    port: 2379
    targetPort: client
    protocol: TCP
